name: flutter_mapbox_autocomplete
description: A Flutter Package for MapBox Places autocomplete which allows you use the MapBox API's to get autocomplete text of places
version: 1.0.4
homepage: https://github.com/lhamycodes/flutter_mapbox_autocomplete

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Lemonada
      fonts:  
        - asset: lib/src/Lemonada-VariableFont_wght.ttf 
